// src/new-tab/components/Dashboard.tsx
import { FC } from 'react';
import { Dapp } from '../model';
import { DappCard } from './DappCard';
import { Box, Grid, Typography } from '@mui/material';
import styled from 'styled-components';

const FAVOURITES: Dapp[] = [
  {
    name: 'NNS',
    canisterId: 'qoctq-giaaa-aaaaa-aaaea-cai',
    url: 'https://nns.ic0.app',
  },
  {
    name: 'Distrikt',
    canisterId: 'az5sd-cqaaa-aaaae-aaarq-cai',
  },
  {
    name: 'Taggr',
    canisterId: '6qfxa-ryaaa-aaaai-qbhsq-cai',
  },
  {
    name: 'Open Chat',
    canisterId: '6hsbt-vqaaa-aaaaf-aaafq-cai',
    url: 'https://oc.app',
  },
];

const GridWrapper = styled(Box)`
  padding: 0 ${props => props.theme.spacing(4)};
  width: 100%;
  display: flex;
  flex-direction: column;
  justify-content: center;
`;

export const Dashboard: FC = () => {
  return (
    <>
      <Typography variant="h2" component="h1" align="center" mt={7} mb={9}>
        Pylon
      </Typography>

      <GridWrapper>
        <Grid
          container
          maxWidth="md"
          rowSpacing={2}
          columnSpacing={2}
          alignSelf={'center'}
        >
          {FAVOURITES.map(dapp => (
            <Grid key={dapp.canisterId} xs={4} sm={3} md={2} item>
              <DappCard dapp={dapp} />
            </Grid>
          ))}
        </Grid>
      </GridWrapper>
    </>
  );
};

// src/renderer/app/core/dashboard/dashboard.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { DappListing } from '../../model';
import { RowComponent, ColumnComponent, ContainerComponent } from '../../ui';
import { DappListingCardComponent } from '../dapp-listing-card';

const DAPP_LISTINGS: DappListing[] = [
  {
    name: 'Internet Computer Docs',
    canisterId: 'hwvjt-wqaaa-aaaam-qadra-cai',
  },
  {
    name: 'Motoko Playground',
    canisterId: 'm7sm4-2iaaa-aaaab-qabra-cai',
  },
  {
    name: 'NNS',
    canisterId: 'qoctq-giaaa-aaaaa-aaaea-cai',
    url: 'https://nns.ic0.app',
  },
  {
    name: 'Internet Identity',
    canisterId: 'rdmx6-jaaaa-aaaaa-aaadq-cai',
    url: 'https://identity.ic0.app',
  },
  {
    name: 'Distrikt',
    canisterId: 'az5sd-cqaaa-aaaae-aaarq-cai',
  },
  {
    name: 'Taggr',
    canisterId: '6qfxa-ryaaa-aaaai-qbhsq-cai',
  },
  {
    name: 'Open Chat',
    canisterId: '6hsbt-vqaaa-aaaaf-aaafq-cai',
    url: 'https://oc.app',
  },
];

@Component({
  selector: 'app-dashboard',
  imports: [
    CommonModule,
    ContainerComponent,
    RowComponent,
    ColumnComponent,
    DappListingCardComponent,
  ],
  standalone: true,
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DashboardComponent {
  public dappListings = DAPP_LISTINGS;
}

<app-container vertical-spacing class="dashboard-container">
  <h1 class="dashboard-title display-3">Pylon</h1>

  <div class="dapp-listings-container">
    <ng-container *ngFor="let dapp of dappListings">
      <app-dapp-listing-card class="dapp-listing" [dappListing]="dapp" (openDapp)="onOpenDapp(dapp)">
      </app-dapp-listing-card>
    </ng-container>
  </div>
</app-container>
